###
GET http://localhost:3000/customers

###
POST http://localhost:3000/customers
Content-Type: application/json

{
    "firstName": "Tien Khanh",
    "lastName": "Nguyen",
    "email": "tienkhanhnguyen@khanh.com",
    "password": "iamsohandsome"
}

### FARMERs ####
GET http://localhost:3000/farmers
###
POST http://localhost:3000/farmers
Content-Type: application/json

{
    "firstName": "Nhan farmer", 
    "lastName": "Ngo",
    "email": "nhan@gmail.com",
    "password": "jksjksds",
    "tel": "642-344-4343",
    "address": "1200 Verill St",
    "reputation": 0
}


### PRODUCTS
GET http://localhost:3000/products

###
GET http://localhost:3000/products/5f317f83d18db035a489edb6
###
PUT http://localhost:3000/products/5f317f83d18db035a489edb6
Content-Type: application/json

{
    "farmer": "5f30378415280f2cc0ca5818",
    "name": "Fresh Corn 2",
    "description": "2Picked at the Peak of Perfection: Our love for vegetables began over 100 years ago in Le Sueur, Minnesota",
    "price": 0.50,
    "photoUrl": "assets/product2.jpg", 
    "inStock": 200
}

###
DELETE http://localhost:3000/products/5f317f83d18db035a489edb6

### get products of farmer
GET http://localhost:3000/farmers/5f30378415280f2cc0ca5818/products

### get order of farmer
GET http://localhost:3000/farmers/5f30378415280f2cc0ca5818/orders
###
POST http://localhost:3000/products
Content-Type: application/json

{
    "farmer": "5f30378415280f2cc0ca5818",
    "name": "Fresh Corn 2",
    "description": "2Picked at the Peak of Perfection: Our love for vegetables began over 100 years ago in Le Sueur, Minnesota",
    "price": 0.25,
    "photoUrl": "assets/product2.jpg", 
    "inStock": 100
}

#### Order ######
GET http://localhost:3000/orders

#### Order by id ######
GET http://localhost:3000/orders/5f30563e3695673c100d4ce9

### Create order ####
POST http://localhost:3000/orders
Content-Type: application/json

{
    "farmerId": "5f30378415280f2cc0ca5818",
    "customerId": "5f30508bf04a4129b4db2a64",
    "productIds": ["5f303b3ff2055644d0553b24"]
}

### Update order status ###
PUT http://localhost:3000/orders/5f30563e3695673c100d4ce9?status=READY
Content-Type: application/json

{}


### get orders of customer
GET http://localhost:3000/customers/5f30508bf04a4129b4db2a64/orders