###
GET http://localhost:3000/customers

###
POST http://localhost:3000/customers
Content-Type: application/json

{
    "firstName": "Tien Khanh 2",
    "lastName": "Nguyen",
    "email": "khanhnt.tdt@gmail.com",
    "password": "iamsohandsome"
}

### FARMERs ####
GET http://localhost:3000/farmers
###
POST http://localhost:3000/farmers
Content-Type: application/json

{
    "firstName": "Nhan farmer", 
    "lastName": "Ngo",
    "email": "chinhan2k5@gmail.com",
    "password": "jksjksds",
    "tel": "642-344-4343",
    "address": "1200 Verill St",
    "reputation": 0
}


### PRODUCTS
GET http://localhost:3000/products

###
GET http://localhost:3000/products/5f31c16b1f34a7138c3e7a9b
###
PUT http://localhost:3000/products/5f31c0e01f34a7138c3e7a9a
Content-Type: application/json

{
    "farmer": "5f30378415280f2cc0ca5818",
    "name": "Fresh Corn 2",
    "description": "2Picked at the Peak of Perfection: Our love for vegetables began over 100 years ago in Le Sueur, Minnesota",
    "price": 0.50,
    "photoUrl": "assets/product2.jpg", 
    "inStock": 200
}

###
DELETE http://localhost:3000/products/5f317f83d18db035a489edb6

### get products of farmer
GET http://localhost:3000/farmers/5f32cf69aac1d435e41265de/products

### get order of farmer
GET http://localhost:3000/farmers/5f32cf69aac1d435e41265de/orders
###
POST http://localhost:3000/products
Content-Type: application/json

{
    "farmer": "5f32d8e68af07e3a582b9e34",
    "name": "Fresh Corn",
    "description": "Picked at the Peak of Perfection: Our love for vegetables began over 100 years ago in Le Sueur, Minnesota",
    "price": 0.25,
    "photoUrl": "https://placeimg.com/500/500/tech?query=1", 
    "inStock": 10
}

###
POST http://localhost:3000/products
Content-Type: application/json

{
    "farmer": "5f32d8e68af07e3a582b9e34",
    "name": "Curcumber super",
    "description": "Picked at the Peak of Perfection: Our love for vegetables began over 100 years ago in Le Sueur, Minnesota",
    "price": 0.40,
    "photoUrl": "https://placeimg.com/500/500/tech?query=2", 
    "inStock": 100
}

#### Order ######
GET http://localhost:3000/orders

#### Order by id ######
GET http://localhost:3000/orders/5f32d6ea862a8236e0faee62

### Create order #### old
POST http://localhost:3000/orders
Content-Type: application/json

{
    "farmerId": "5f30378415280f2cc0ca5818",
    "customerId": "5f30508bf04a4129b4db2a64",
    "productIds": ["5f303b3ff2055644d0553b24"]
}

### Create order #### new ok order
POST http://localhost:3000/orders
Content-Type: application/json

{
    "farmerId": "5f32d8e68af07e3a582b9e34",
    "customerId": "5f32d8f08af07e3a582b9e35",
    "orderItems": [
        {"_id":"5f32cfcfaac1d435e41265e0", "quantity": 2},        
        {"_id":"5f32d9ba8af07e3a582b9e37", "quantity": 3}
    ]
}
### Test Create order over stock and not exits product
POST http://localhost:3000/orders
Content-Type: application/json

{
    "farmerId": "5f32d8e68af07e3a582b9e34",
    "customerId": "5f32d6ea862a8236e0faee62",
    "orderItems": [{"_id":"5f31c16b1f34a7138c3e7a9b", "quantity": 101}, {"_id":"5f31c16b1f34a7138c3e7a9a", "quantity": 101} ]
}

### Update order status ###
PUT http://localhost:3000/orders/5f32d722862a8236e0faee64?status=READY
Content-Type: application/json

{}


### get orders of customer
GET http://localhost:3000/customers/5f32d6ea862a8236e0faee62/orders


### test mail
POST http://localhost:3000/orders/sendmailtest
Content-Type: application/json

{
    "to": "khanhnt.tdt@gmail.com",
    "subject" : "give me your money or die",
    "text": "give me your money or die"

}